
### peticion de saludo
GET http://localhost:3000/saludo/juan


### lista de productos
GET http://localhost:3000/productos


### producto por id
GET http://localhost:3000/productos/a0872e7c-7dc6-4114-b6e4-9d4bfbe4a77a



### agregar producto
POST http://localhost:3000/productos
Content-Type: application/json 

{
    "title": "Otro producto mas",
    "description": "Esta debe ser una descripción de al menos 20 caracteres",
    "price": 10,
    "category": "jewelery",
    "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"
}

### eliminar producto

DELETE http://localhost:3000/productos/78bbf31f-ca46-46bb-b371-d9d94a3bc624